"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { Fira_Code } from 'next/font/google';
import { Roboto_Mono,Lato } from 'next/font/google';
import { Toaster } from "@/components/ui/sonner"
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { AnimatePresence } from "framer-motion";
import { motion } from "framer-motion";
const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify the weights you need
  style: ['normal', 'italic'], // Optional: Add styles if required
  variable: '--font-lato', // Optional: Add a CSS variable
  display: 'swap', // Controls font rendering behavior
});
import { usePathname } from "next/navigation";

const robotoMono = Roboto_Mono({
  subsets: ['latin'], // Choose the subset you need
  weight: ['400', '700'], // Optional: specify font weights
});

const firaCode = Fira_Code({
  subsets: ['latin'], // Choose the subset you need
  weight: ['400', '700'], // Optional: specify font weights
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname=usePathname();
  return (
   <ClerkProvider>
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={lato.className}
      >

        <Navbar></Navbar>
        {children}
        {/* <AnimatePresence mode="wait">
          
          <motion.div
           key={pathname}
           initial={{opacity:0}}
           animate={{opacity:1}}
           exit={{opacity:0}}
           transition={{duration:2}}
          
          >
          
          </motion.div>



        </AnimatePresence> */}
        
        
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
